// Warning pollution, agent should generate up to 3 tickets describing Deprecated API endpoint usage, slower queries, and auth service connection pool nearing capacity
export const LOGS = [
    { "time": "15:00:07", "service": "database-service", "level": "WARN", "msg": "Connection pool at 75% capacity", "request_id": "req_l959jddr" },
    { "time": "15:00:19", "service": "auth-service", "level": "WARN", "msg": "Connection pool at 75% capacity", "user_id": "user_18519" },
    { "time": "15:01:12", "service": "database-service", "level": "WARN", "msg": "Deprecated API endpoint used" },
    { "time": "15:01:19", "service": "auth-service", "level": "WARN", "msg": "Slow query detected" },
    { "time": "15:01:23", "service": "order-service", "level": "WARN", "msg": "Deprecated API endpoint used" },
    { "time": "15:02:20", "service": "database-service", "level": "WARN", "msg": "Slow query detected", "request_id": "req_lwdp2zwj", "user_id": "user_57393" },
    { "time": "15:02:22", "service": "database-service", "level": "WARN", "msg": "Slow query detected", "request_id": "req_cm1f6j3f" },
    { "time": "15:02:36", "service": "payment-service", "level": "WARN", "msg": "Slow query detected", "request_id": "req_5ykikqfq" },
    { "time": "15:04:08", "service": "auth-service", "level": "WARN", "msg": "Slow query detected" },
    { "time": "15:04:11", "service": "auth-service", "level": "WARN", "msg": "Connection pool at 75% capacity", "request_id": "req_he79rb7n" },
    { "time": "15:06:09", "service": "auth-service", "level": "WARN", "msg": "Connection pool at 75% capacity", "request_id": "req_pg0b3jx9", "user_id": "user_77100" },
    { "time": "15:06:25", "service": "auth-service", "level": "WARN", "msg": "Slow query detected", "request_id": "req_p1mzth5d" },
    { "time": "15:06:26", "service": "payment-service", "level": "WARN", "msg": "Deprecated API endpoint used", "request_id": "req_8h5aji08" },
    { "time": "15:07:30", "service": "auth-service", "level": "WARN", "msg": "Deprecated API endpoint used", "request_id": "req_t7jesidf" },
    { "time": "15:07:47", "service": "api-gateway", "level": "WARN", "msg": "Connection pool at 75% capacity", "user_id": "user_99291" },
    { "time": "15:08:27", "service": "database-service", "level": "WARN", "msg": "Connection pool at 75% capacity", "request_id": "req_vakq8x5r" },
    { "time": "15:09:51", "service": "auth-service", "level": "WARN", "msg": "Deprecated API endpoint used", "request_id": "req_c2at7fhv", "user_id": "user_19156" },
    { "time": "15:10:25", "service": "payment-service", "level": "WARN", "msg": "Deprecated API endpoint used", "user_id": "user_22267" },
    { "time": "15:10:44", "service": "database-service", "level": "WARN", "msg": "Connection pool at 75% capacity" },
    { "time": "15:10:56", "service": "payment-service", "level": "WARN", "msg": "Slow query detected", "request_id": "req_p1mzth5d" },
    { "time": "15:11:09", "service": "payment-service", "level": "WARN", "msg": "Slow query detected" },
    { "time": "15:11:13", "service": "auth-service", "level": "WARN", "msg": "Connection pool at 75% capacity", "user_id": "user_58810" },
    { "time": "15:11:30", "service": "order-service", "level": "WARN", "msg": "Connection pool at 75% capacity", "request_id": "req_bhlk1ksg" },
    { "time": "15:12:18", "service": "order-service", "level": "WARN", "msg": "Slow query detected", "user_id": "user_50580" },
    { "time": "15:12:19", "service": "payment-service", "level": "WARN", "msg": "Slow query detected", "user_id": "user_74895" },
    { "time": "15:14:30", "service": "auth-service", "level": "WARN", "msg": "Slow query detected" },
    { "time": "15:14:53", "service": "auth-service", "level": "WARN", "msg": "Slow query detected", "request_id": "req_8yswyb62", "user_id": "user_33562" },
    { "time": "15:14:54", "service": "payment-service", "level": "WARN", "msg": "Connection pool at 75% capacity", "user_id": "user_84115" },
    { "time": "15:15:16", "service": "database-service", "level": "WARN", "msg": "Slow query detected", "request_id": "req_7ju74eep", "user_id": "user_42561" },
    { "time": "15:15:23", "service": "api-gateway", "level": "WARN", "msg": "Slow query detected", "request_id": "req_2tcdotxd" },
    { "time": "15:16:49", "service": "order-service", "level": "WARN", "msg": "Connection pool at 75% capacity", "request_id": "req_ffilsflg" },
    { "time": "15:16:57", "service": "api-gateway", "level": "WARN", "msg": "Deprecated API endpoint used" },
    { "time": "15:17:01", "service": "order-service", "level": "WARN", "msg": "Deprecated API endpoint used", "user_id": "user_14914" },
    { "time": "15:17:33", "service": "payment-service", "level": "WARN", "msg": "Slow query detected" },
    { "time": "15:18:38", "service": "auth-service", "level": "WARN", "msg": "Slow query detected", "request_id": "req_5ahj6sn5" },
    { "time": "15:19:37", "service": "auth-service", "level": "WARN", "msg": "Slow query detected", "request_id": "req_j89ti8lm", "user_id": "user_49354" },
    { "time": "15:19:41", "service": "api-gateway", "level": "WARN", "msg": "Slow query detected" },
    { "time": "15:19:59", "service": "payment-service", "level": "WARN", "msg": "Deprecated API endpoint used" },
    { "time": "15:21:52", "service": "order-service", "level": "WARN", "msg": "Deprecated API endpoint used", "request_id": "req_lwdp2zwj" },
    { "time": "15:22:01", "service": "api-gateway", "level": "WARN", "msg": "Deprecated API endpoint used", "request_id": "req_zqipwy04", "user_id": "user_86414" },
    { "time": "15:22:35", "service": "api-gateway", "level": "WARN", "msg": "Slow query detected", "request_id": "req_ii8zlary", "user_id": "user_47740" },
    { "time": "15:22:50", "service": "api-gateway", "level": "WARN", "msg": "Deprecated API endpoint used", "request_id": "req_cicy26fz", "user_id": "user_68411" },
    { "time": "15:25:32", "service": "auth-service", "level": "WARN", "msg": "Connection pool at 75% capacity", "request_id": "req_s7hjslbg" },
    { "time": "15:27:28", "service": "database-service", "level": "WARN", "msg": "Deprecated API endpoint used", "user_id": "user_97641" },
    { "time": "15:29:05", "service": "api-gateway", "level": "WARN", "msg": "Deprecated API endpoint used", "request_id": "req_o7349idf", "user_id": "user_19594" },
    { "time": "15:30:28", "service": "database-service", "level": "WARN", "msg": "Connection pool at 75% capacity", "request_id": "req_ulhwc6fa", "user_id": "user_86748" },
    { "time": "15:31:45", "service": "api-gateway", "level": "WARN", "msg": "Connection pool at 75% capacity" },
    { "time": "15:31:56", "service": "api-gateway", "level": "WARN", "msg": "Slow query detected", "user_id": "user_45381" },
    { "time": "15:32:08", "service": "payment-service", "level": "WARN", "msg": "Slow query detected", "request_id": "req_vwhnfhjv", "user_id": "user_75066" },
    { "time": "15:32:57", "service": "order-service", "level": "WARN", "msg": "Connection pool at 75% capacity", "request_id": "req_a6p3o5qf" },
    { "time": "15:33:39", "service": "database-service", "level": "WARN", "msg": "Connection pool at 75% capacity", "request_id": "req_f7y6g2et" },
    { "time": "15:33:58", "service": "database-service", "level": "WARN", "msg": "Slow query detected", "request_id": "req_zatpalws" },
    { "time": "15:35:29", "service": "order-service", "level": "WARN", "msg": "Deprecated API endpoint used", "user_id": "user_83434" },
    { "time": "15:37:44", "service": "auth-service", "level": "WARN", "msg": "Slow query detected", "user_id": "user_87905" },
    { "time": "15:37:53", "service": "auth-service", "level": "WARN", "msg": "Slow query detected", "request_id": "req_4e7z6kno" },
    { "time": "15:39:16", "service": "order-service", "level": "WARN", "msg": "Connection pool at 75% capacity", "request_id": "req_irvjapnu" },
    { "time": "15:39:36", "service": "payment-service", "level": "WARN", "msg": "Deprecated API endpoint used", "request_id": "req_pjy7ibmp" },
    { "time": "15:41:31", "service": "auth-service", "level": "WARN", "msg": "Deprecated API endpoint used" },
    { "time": "15:41:32", "service": "order-service", "level": "WARN", "msg": "Slow query detected", "user_id": "user_19156" },
    { "time": "15:41:33", "service": "auth-service", "level": "WARN", "msg": "Connection pool at 75% capacity" },
    { "time": "15:41:34", "service": "auth-service", "level": "WARN", "msg": "Connection pool at 75% capacity", "request_id": "req_khzrdwc2" }
]

// No changes
export const RECENT_CHANGES = []