// Obvious Critical Errors, no clear indication or way to explore more; agent should alert team
export const LOGS = [
    { "time": "16:11:24", "service": "order-service", "level": "INFO", "msg": "Order created" },
    { "time": "16:11:30", "service": "api-gateway", "level": "INFO", "msg": "Request processed" },
    { "time": "16:11:36", "service": "auth-service", "level": "INFO", "msg": "Payment authorized" },
    { "time": "16:11:42", "service": "payment-service", "level": "INFO", "msg": "Order created" },
    { "time": "16:11:48", "service": "auth-service", "level": "INFO", "msg": "Latency within SLA" },
    { "time": "16:11:54", "service": "api-gateway", "level": "INFO", "msg": "Order created" },
    { "time": "16:12:00", "service": "payment-service", "level": "ERROR", "msg": "Failed to connect to payment.processor.com - connection refused" },
    { "time": "16:12:03", "service": "payment-service", "level": "ERROR", "msg": "CRITICAL: Payment processor API is unreachable" },
    { "time": "16:12:06", "service": "auth-service", "level": "INFO", "msg": "Cache hit" },
    { "time": "16:12:09", "service": "payment-service", "level": "ERROR", "msg": "Payment processing failed - external service unavailable" },
    { "time": "16:12:12", "service": "payment-service", "level": "ERROR", "msg": "Failed to connect to payment.processor.com - connection refused" },
    { "time": "16:12:15", "service": "payment-service", "level": "ERROR", "msg": "Payment processing failed - external service unavailable" },
    { "time": "16:12:18", "service": "database-service", "level": "INFO", "msg": "Payment authorized" },
    { "time": "16:12:21", "service": "payment-service", "level": "ERROR", "msg": "Failed to connect to payment.processor.com - connection refused" },
    { "time": "16:12:24", "service": "auth-service", "level": "INFO", "msg": "Latency within SLA" },
    { "time": "16:12:27", "service": "api-gateway", "level": "INFO", "msg": "Order created" },
    { "time": "16:12:30", "service": "payment-service", "level": "ERROR", "msg": "Failed to connect to payment.processor.com - connection refused" },
    { "time": "16:12:33", "service": "payment-service", "level": "ERROR", "msg": "Failed to connect to payment.processor.com - connection refused" },
    { "time": "16:12:36", "service": "api-gateway", "level": "INFO", "msg": "Inventory checked" },
    { "time": "16:12:39", "service": "payment-service", "level": "ERROR", "msg": "CRITICAL: Payment processor API is unreachable" },
    { "time": "16:12:42", "service": "database-service", "level": "INFO", "msg": "Session validated" },
    { "time": "16:12:45", "service": "payment-service", "level": "ERROR", "msg": "CRITICAL: Payment processor API is unreachable" },
    { "time": "16:12:48", "service": "payment-service", "level": "ERROR", "msg": "CRITICAL: Payment processor API is unreachable" },
    { "time": "16:12:51", "service": "payment-service", "level": "ERROR", "msg": "CRITICAL: Payment processor API is unreachable" },
    { "time": "16:12:54", "service": "order-service", "level": "INFO", "msg": "Session validated" },
    { "time": "16:12:57", "service": "payment-service", "level": "ERROR", "msg": "Payment processing failed - external service unavailable" },
    { "time": "16:13:00", "service": "database-service", "level": "INFO", "msg": "Order created" },
    { "time": "16:13:03", "service": "payment-service", "level": "ERROR", "msg": "Payment processing failed - external service unavailable" },
    { "time": "16:13:06", "service": "payment-service", "level": "ERROR", "msg": "CRITICAL: Payment processor API is unreachable" },
    { "time": "16:13:09", "service": "payment-service", "level": "ERROR", "msg": "Payment processing failed - external service unavailable" },
    { "time": "16:13:12", "service": "payment-service", "level": "ERROR", "msg": "Failed to connect to payment.processor.com - connection refused" },
    { "time": "16:13:15", "service": "order-service", "level": "INFO", "msg": "Session validated" },
    { "time": "16:13:18", "service": "payment-service", "level": "ERROR", "msg": "Failed to connect to payment.processor.com - connection refused" },
    { "time": "16:13:21", "service": "payment-service", "level": "ERROR", "msg": "Payment processing failed - external service unavailable" },
    { "time": "16:13:24", "service": "database-service", "level": "INFO", "msg": "Product page viewed" },
    { "time": "16:13:27", "service": "api-gateway", "level": "INFO", "msg": "Request processed" },
    { "time": "16:13:30", "service": "payment-service", "level": "ERROR", "msg": "Failed to connect to payment.processor.com - connection refused" },
    { "time": "16:13:33", "service": "order-service", "level": "INFO", "msg": "User login successful" },
    { "time": "16:13:36", "service": "auth-service", "level": "INFO", "msg": "Payment authorized" },
    { "time": "16:13:39", "service": "payment-service", "level": "ERROR", "msg": "Failed to connect to payment.processor.com - connection refused" },
    { "time": "16:13:42", "service": "payment-service", "level": "ERROR", "msg": "Payment processing failed - external service unavailable" },
    { "time": "16:13:45", "service": "payment-service", "level": "ERROR", "msg": "Failed to connect to payment.processor.com - connection refused" },
    { "time": "16:13:48", "service": "payment-service", "level": "ERROR", "msg": "Payment processing failed - external service unavailable" },
    { "time": "16:13:51", "service": "payment-service", "level": "ERROR", "msg": "CRITICAL: Payment processor API is unreachable" },
    { "time": "16:13:54", "service": "auth-service", "level": "INFO", "msg": "Order created" },
    { "time": "16:13:57", "service": "payment-service", "level": "ERROR", "msg": "CRITICAL: Payment processor API is unreachable" },
    { "time": "16:14:00", "service": "payment-service", "level": "ERROR", "msg": "Failed to connect to payment.processor.com - connection refused" },
    { "time": "16:14:03", "service": "auth-service", "level": "INFO", "msg": "Cache hit" },
    { "time": "16:14:06", "service": "api-gateway", "level": "INFO", "msg": "Database query completed" },
    { "time": "16:14:09", "service": "api-gateway", "level": "INFO", "msg": "Order created" },
    { "time": "16:14:12", "service": "auth-service", "level": "INFO", "msg": "Session validated" },
    { "time": "16:14:15", "service": "payment-service", "level": "ERROR", "msg": "CRITICAL: Payment processor API is unreachable" },
    { "time": "16:14:18", "service": "payment-service", "level": "ERROR", "msg": "Payment processing failed - external service unavailable" },
    { "time": "16:14:21", "service": "payment-service", "level": "ERROR", "msg": "CRITICAL: Payment processor API is unreachable" },
    { "time": "16:14:24", "service": "order-service", "level": "INFO", "msg": "Session validated" },
    { "time": "16:14:27", "service": "payment-service", "level": "ERROR", "msg": "Payment processing failed - external service unavailable" },
    { "time": "16:14:30", "service": "auth-service", "level": "INFO", "msg": "Payment authorized" },
    { "time": "16:14:33", "service": "database-service", "level": "INFO", "msg": "Payment authorized" },
    { "time": "16:14:36", "service": "payment-service", "level": "ERROR", "msg": "Payment processing failed - external service unavailable" },
    { "time": "16:14:39", "service": "api-gateway", "level": "INFO", "msg": "Shipping quote calculated" },
    { "time": "16:14:42", "service": "payment-service", "level": "ERROR", "msg": "Failed to connect to payment.processor.com - connection refused" },
    { "time": "16:14:45", "service": "payment-service", "level": "ERROR", "msg": "Payment processing failed - external service unavailable" },
    { "time": "16:14:48", "service": "database-service", "level": "INFO", "msg": "Cache hit" },
    { "time": "16:14:51", "service": "payment-service", "level": "ERROR", "msg": "Payment processing failed - external service unavailable" },
    { "time": "16:14:54", "service": "payment-service", "level": "ERROR", "msg": "Failed to connect to payment.processor.com - connection refused" },
    { "time": "16:14:57", "service": "api-gateway", "level": "INFO", "msg": "User login successful" },
]

// No relevant changes
export const RECENT_CHANGES = [
    {
        "timestamp": "14:34:17",
        "type": "deployment",
        "description": "Update docs",
        "filesAffected": ["README.md"]
    },
]